export const gamesRanks = {
  lolRanks: [
    "Iron 1",
    "Iron 2",
    "Iron 3",
    "Iron 4",
    "Bronze 1",
    "Bronze 2",
    "Bronze 3",
    "Bronze 4",
    "Silver 1",
    "Silver 2",
    "Silver 3",
    "Silver 4",
    "Gold 1",
    "Gold 2",
    "Gold 3",
    "Gold 4",
    "Platinium 1",
    "Platinium 2",
    "Platinium 3",
    "Platinium 4",
    "Diamond 1",
    "Diamond 2",
    "Diamond 3",
    "Diamond 4",
    "Mastertier",
    "Grandmaster",
    "Challanger",
  ],

  valoRanks: [
    "Iron 1",
    "Iron 2",
    "Iron 3",
    "Bronze 1",
    "Bronze 2",
    "Bronze 3",
    "Silver 1",
    "Silver 2",
    "Silver 3",
    "Gold 1",
    "Gold 2",
    "Gold 3",
    "Platinum 1",
    "Platinum 2",
    "Platinum 3",
    "Diamond 1",
    "Diamond 2",
    "Diamond 3",
    "Ascendant 1",
    "Ascendant 2",
    "Ascendant 3",
    "Immortal 1",
    "Immortal 2",
    "Immortal 3",
    "Radiant",
  ],

  csgoRanks: [
    "Silver 1",
    "Silver 2",
    "Silver 3",
    "Silver 4",
    "Silver Elite",
    "Silver Elite Master",
    "Gold Nova 1",
    "Gold Nova 2",
    "Gold Nova 3",
    "Gold Nova Master",
    "Master Guardian 1",
    "Master Guardian 2",
    "Master Guardian Elite",
    "Distinguished Master Guardian",
    "Legendary Eagle",
    "Legendary Eagle Master",
    "Supreme Master First Class",
    "Global Elite",
  ],
};
